
# Site settings
title: BSides Munich
subtitle: "A free security conference in the heart of Bavaria"
url: "https://www.bsidesmunich.org" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

collections:
  talks:
    output: true #Does not work
    permalink: /:collection/:title/
#    /:collection/:title/index.html
  workshops:
    output: true #Does not work
    permalink: /:collection/:title/
#    permalink: /:collection/:title

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

imprint:
  #name: "BSides Munich, Mr. Frederic Mohr"
  name: "Muc:Sec e.V."
  addressco: "c/o LastBreach"
  address: "Rohrauerstraße 70, 81477 München"
  email: "info [at] bsidesmunich [dot] org"
  #phone: "+49 89

conference:
  # contact e-mail, e.g., for sponsors
  email: organizers@bsidesmunich.org
  twitter: https://twitter.com/bsidesmunich
  newsletter: http://eepurl.com/dNWt2w
  sponsors:
    #show the sponsors in the footer of every page
    lookingfor: false #BETA
    footer: false #BETA
    # sponsor logos should all have the same format (at least width)
# uncomment it to fill sponsors in
    platinum:
    - name: 
      logo: 
      uri: 
    gold:
    - name: 
      logo: 
      uri: 
    silver:
    - name: 
      logo: 
      uri: 
    bronze:
    - name: 
      logo: 
      uri: 
    community:
    - name: Elbsides
      logo: /img/sponsors/elbsides.png
      uri: https://elbsides.de/

  links:
    sponsorpackage_en_uri: 
    sponsorpackage_de_uri: 
    cfw_uri: 
    cfp_uri: 
    contickets_uri: 
    contickets_state: 
  archive:
    a2020:
      title: "BSides Munich 2020"
      participants: 
      presentations: 
      workshops: 
      hours: 
      website_uri: https://2020.bsidesmunich.org
      recordings_uri: 
      cancelled: "BSidesMunich 2020 is going Virtual - BSMaaS:2020.08.23"
    a2019:
      title: "BSides Munich 2019"
      participants: 343
      presentations: 13
      workshops: 8
      hours: 38
      website_uri: https://2019.bsidesmunich.org
      recordings_uri: https://www.youtube.com/watch?v=u8twBNM7LmQ&list=PL8N5HiRDvZ-f063NRSyVm4gEycdI54ZXD
      slider:
      - src: img/slider2019/IMG_20190325_112110.jpg
      - src: img/slider2019/IMG_20190329_170605.jpg
      - src: img/slider2019/P3240090.jpg
      - src: img/slider2019/P3240167.jpg
      - src: img/slider2019/P3250641.jpg
      - src: img/slider2019/P3250925.jpg
    a2018:
      title: "BSides Munich 2018"
      participants: 300
      presentations: 15
      workshops: 6
      hours: 35
      website_uri: https://2018.bsidesmunich.org
      recordings_uri: https://www.youtube.com/watch?v=zq2Ge3EQMpE&list=PL8N5HiRDvZ-etExLvF5766VOD0CkZTSZx
      slider:
      - src: img/slider2018/organizers.jpg
      - src: img/slider2018/MS-P4080195.jpg
      - src: img/slider2018/MS-P4090241.jpg
      - src: img/slider2018/MS-P4090485.jpg
      - src: img/slider2018/MS-P4090947.jpg
    a2017:
      title: "BSides Munich 2017"
      participants: 78
      presentations: 10
      workshops: 3
      hours: 16
      website_uri: http://2017.bsidesmunich.org
      recordings_uri: https://www.youtube.com/watch?v=k_D3GzzJ5hA&list=PL8N5HiRDvZ-dL4MElY5NUKmaqDmI7QfVy
      archiveorg_uri: https://archive.org/details/BSidesMunich2017
      slider:
      - src: img/slider2017/organizers.jpg
      - src: img/slider2017/IMG_20170403_145820.jpg
      - src: img/slider2017/P4030023.jpg
      - src: img/slider2017/P4030056.jpg
      - src: img/slider2017/P4030102.jpg
      - src: img/slider2017/P4030244.jpg
      - src: img/slider2017/P4030312.jpg
      - src: img/slider2017/P4030371.jpg
      - src: img/slider2017/P4030518.jpg
      - src: img/slider2017/P4030577.jpg
      - src: img/slider2017/P4030676.jpg
      - src: img/slider2017/P4030704.jpg
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: []
  blanklines: false
  profile: false

exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "Makefile"
  - "INSTALL.txt"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

pre_build:
  commands:
    - export LC_ALL="C.UTF-8"
    - export LANG="en_US.UTF-8"
    - export LANGUAGE="en_US.UTF-8"
